INSERT INTO teachers(name) VALUES ('Samuel Bennett');
INSERT INTO teachers(name) VALUES ('Olivia Harper');
INSERT INTO teachers(name) VALUES ('Lucas Ford');
INSERT INTO teachers(name) VALUES ('Grace Mitchell');
INSERT INTO teachers(name) VALUES ('Benjamin Ramirez');
INSERT INTO teachers(name) VALUES ('Hannah Ortiz');
INSERT INTO teachers(name) VALUES ('Gabriel Walker');
INSERT INTO teachers(name) VALUES ('Emily Wright');
INSERT INTO teachers(name) VALUES ('Isaac Foster');
INSERT INTO teachers(name) VALUES ('Leah Simpson');
INSERT INTO teachers(name) VALUES ('Julian Hayes');
INSERT INTO teachers(name) VALUES ('Bella Russell');
INSERT INTO teachers(name) VALUES ('Wyatt Coleman');
INSERT INTO teachers(name) VALUES ('Amelia Fernandez');
INSERT INTO teachers(name) VALUES ('Tristan Lynch');

INSERT INTO courses(course_name, teacher_id) VALUES ('CS-101: Introduction to Programming', 1);
INSERT INTO courses(course_name, teacher_id) VALUES ('CS-102: Data Structures and Algorithms', 2);
INSERT INTO courses(course_name, teacher_id) VALUES ('CS-103: Web Development Basics', 3);
INSERT INTO courses(course_name, teacher_id) VALUES ('CS-104: Object-Oriented Programming', 4);
INSERT INTO courses(course_name, teacher_id) VALUES ('CS-105: Software Engineering Principles', 5);
INSERT INTO courses(course_name, teacher_id) VALUES ('CS-106: Database Systems', 6);
INSERT INTO courses(course_name, teacher_id) VALUES ('CS-107: Network Fundamentals', 7);
INSERT INTO courses(course_name, teacher_id) VALUES ('CS-108: Mobile App Development', 8);
INSERT INTO courses(course_name, teacher_id) VALUES ('CS-109: Operating Systems Concepts', 9);
INSERT INTO courses(course_name, teacher_id) VALUES ('CS-110: Artificial Intelligence Foundations', 10);
INSERT INTO courses(course_name, teacher_id) VALUES ('CS-111: Cloud Computing Essentials', 11);
INSERT INTO courses(course_name, teacher_id) VALUES ('CS-112: Cybersecurity Basics', 12);
INSERT INTO courses(course_name, teacher_id) VALUES ('CS-113: Game Development Introduction', 13);
INSERT INTO courses(course_name, teacher_id) VALUES ('CS-114: Human-Computer Interaction', 14);
INSERT INTO courses(course_name, teacher_id) VALUES ('CS-115: Computational Theory', 15);